[package]
edition = "2021"
name = "connect-x"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21"
egui-macroquad = "0.12"
macroquad = "0.3"
ndarray = "0.15"
