[package]
edition = "2021"
name = "connect-x"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "=0.8.0"
egui = "0.19"
egui-macroquad = "0.12"
macroquad = "0.3"
